variables:
  watcherTrigger: 
    
    exclude: ['*']
    paths: 
      include: ['INPUT/watcher_automation_input.xlsm']

  ruleTrigger:  
    
    exclude: ['*']
    paths:
      include: ['INPUT/rules_automation_input.xlsm']

jobs:
- job: RunPythonScriptWatcher
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - script: |
        pip install -r requirements.txt
        python AUTOMATION/watcher_automation.py
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop02'
        publishLocation: 'Container'

- job: RunPythonScriptRules
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - script: |
        pip install -r requirements.txt
        python AUTOMATION/rule_generator.py
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'another_drop02'
        publishLocation: 'Container'

